# Generated by Django 3.0.3 on 2020-02-08 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('preview', models.TextField(max_length=600, verbose_name='Preview')),
                ('content', models.TextField(max_length=2000, verbose_name='Detail Text')),
                ('Name', models.CharField(max_length=250, verbose_name='Address')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('arbitrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Arbitrator', to=settings.AUTH_USER_MODEL)),
                ('editedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_last_edited_by', to=settings.AUTH_USER_MODEL)),
                ('publishedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_published_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('preview', models.TextField(max_length=600, verbose_name='Preview')),
                ('content', models.TextField(max_length=2000, verbose_name='Detail Text')),
                ('category', models.CharField(choices=[('sport', 'Sport'), ('news', 'News'), ('donation', 'Donation'), ('match', 'Match'), ('project', 'Project')], max_length=64)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('editedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_last_edited_by', to=settings.AUTH_USER_MODEL)),
                ('publishedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_published_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('goalkeeper', 'Goalkeeper'), ('attack', 'Attack'), ('defense', 'Defense')], max_length=20, verbose_name='Position in the game')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_played', to='crmapp.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=14, unique=True)),
                ('first_name', models.CharField(max_length=64, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Name', models.CharField(max_length=250, verbose_name='Address')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('position', models.CharField(blank=True, choices=[('PRESIDENT', 'PRESIDENT'), ('ADMINISTRATION', 'ADMINISTRATION'), ('MEMBER', 'MEMBER'), ('OTHER', 'OTHER')], max_length=255, null=True, verbose_name='Position at the Association')),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created Att')),
                ('isActive', models.BooleanField(default=False)),
                ('activatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_activated_by', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
