# Generated by Django 3.0.4 on 2020-07-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_auto_20200726_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='account',
            name='isActive',
        ),
    ]
