# Generated by Django 3.0.4 on 2020-08-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_account_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_Accepted',
            field=models.BooleanField(),
        ),
    ]
