# Generated by Django 3.0.4 on 2020-08-02 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_auto_20200801_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='Name',
            new_name='address',
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.date(2020, 8, 12), verbose_name='Date play'),
        ),
    ]
