# Generated by Django 3.0.4 on 2020-08-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_auto_20200802_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(null=True, verbose_name='Maximum of Players'),
        ),
    ]
