# Generated by Django 3.0.4 on 2020-08-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_game_max_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='max_players',
        ),
    ]
