# Generated by Django 3.0.4 on 2020-08-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_remove_game_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(null=True, verbose_name='Maximum of Players'),
        ),
    ]
