# Generated by Django 3.0.4 on 2020-08-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0012_game_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('WAITINGLIST', 'Waiting List')], default='REGISTERED', max_length=20, verbose_name='Status of the registration'),
            preserve_default=False,
        ),
    ]
