# Generated by Django 3.0.4 on 2020-08-03 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmapp', '0013_gameregistration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameregistration',
            name='game',
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(verbose_name='Date play'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='team_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='crmapp.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='crmapp.Team'),
        ),
        migrations.AddField(
            model_name='gameregistration',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_joined', to='crmapp.Team'),
            preserve_default=False,
        ),
    ]
