# Generated by Django 3.0.4 on 2020-08-03 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmapp', '0014_auto_20200803_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='publishedBy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_published_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='crmapp.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='crmapp.Team'),
        ),
    ]
