# Generated by Django 3.0.4 on 2020-08-04 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmapp', '0015_auto_20200804_0007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameRegistration',
            new_name='TeamRegistration',
        ),
        migrations.AlterField(
            model_name='game',
            name='editedBy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='publishedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_published_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
