# Generated by Django 3.0.4 on 2020-08-29 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0016_auto_20200804_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_team_a', to='crmapp.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_team_b', to='crmapp.Team'),
        ),
    ]
