# Generated by Django 3.0.3 on 2020-03-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
